services:
  todosDB:
    image: postgres:15-alpine
    container_name: todos-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=admin-todo
      
    volumes:
      - ./postgres:/var/lib/postgresql/data
      